[build]
# Target musl-libc by default when running Cargo.
target = "x86_64-unknown-linux-musl"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"
